name: ${project.name}
main: com.mast3rplan.alphachest.acPlugin
version: ${project.version}
website: http://mc.mast3rplan.com/
author: Mast3rPlan
description: >
             Plugin that allows you to have private chests.
commands:
    chest:
        description: The base chest command for Alpha Chest
        usage: |
              /<command> - Opens your private chest.
              /<command> [player] - Opens someone else's chest.
    clearchest:
        description: Clears a chest
        usage: |
              /<command> - Clears your private chest.
              /<command> [player] - Clears someone else's chest.
    savechests:
        description: Saves the chests
        usage: |
              /<command> - Saves all chests.
    reloadchests:
        description: Reloads the seperate configuration file if in-use.
        usage: |
              /<command> - Reloads the seperate configuration file if in-use.