name: ${project.name}
main: net.sradonia.bukkit.alphachest.AlphaChestPlugin
version: ${project.version}
author: kroimon
description: >
             Plugin that allows you to have virtual private chests.

commands:
    chest:
        description: Opens a virtual player-specific chest.
        usage: |
              /<command> - Opens your private chest.
              /<command> [player] - Opens someone else's chest.
        permission: alphachest.chest
    clearchest:
        description: Clears the contents of a chest.
        usage: |
              /<command> - Clears your private chest.
              /<command> [player] - Clears someone else's chest.
        permission: alphachest.chest
    savechests:
        description: Saves the chests to disk.
        permission: alphachest.save
    workbench:
        aliases: [craft, craftbox, craftingbox]
        description: Opens a virtual workbench.
        permission: alphachest.workbench

permissions:
    alphachest.*:
        description: Gives access to the virtual chest and workbench.
        children:
            alphachest.chest: true
            alphachest.workbench: true
    alphachest.chest:
        description: Gives access to the virtual chest.
    alphachest.workbench:
        description: Gives access to the virtual workbench.

    alphachest.keepOnDeath:
        description: Allows to keep the chest contents on death even if clearOnDeath setting is enabled.

    alphachest.admin:
        description: Allows to open and clear someone else's chest.
        default: op
    alphachest.save:
        description: Allows to save all virtual chests.
        default: op
